# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Edify
email: kristen@edifyedu.com
description: 'Edify is a learning & development consultancy that removes the pain of people operations with stellar onboarding, manager development, and knowledge management.'
# baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://edifyedu.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: edifyedu
github_username:  edifyedu
timezone: America/Los_Angeles

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock
  - config.ru
  - Procfile
  - READMD.md
  - vendor

collections:
  posts:
    output: true
    permalink: /blogs/:title

# Jekyll-paginate-v2

autopages:
  enabled: true

pagination:
  enabled: true
  per_page: 5
  permalink: '/:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

#Prose.io config details
prose:
  media: 'img/blog'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
    - .gitignore
    - config.ru
    - feed.xml
    - Gemfile
    - Gemfile.lock
    - Procfile
    - Rakefile
    - README.md

  metadata:
    _pages:
      - name: "layout"
        field:
          element: "hidden"
          value: "page-layout"
      - name: "title"
        field:
          element: "text"
          label: "title"
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "single-post-layout"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "date"
        field:
          element: "text"
          label: "Publish Date"
          help: "Use this date field to indicate the most current date this post was updated. Format: Month Date, Year. This allows you to update posts without breaking a link by changing the date in the file name"
          placeholder: "January 1, 2017"
      - name: "category"
        field:
          element: "multiselect"
          label: "Add Category"
          help: "Select a category from the dropdown menu. If you need a new category, leave this field blank and enter the new category in the text field below. Leave the field below blank if you use this field to select an existing category."
          placeholder: "Choose Category"
          alterable: true
          options:
            - name: "Alternative Learning"
              value: "alternative_learning"
            - name: "Onboarding"
              value: "onboarding"
            - name: "Learning Management"
              value: "learning_management"
            - name: "Managers"
              value: "managers"
            - name: "Instructional Design"
              value: "instructional_design"
            - name: "Human Centered Design"
              value: "human_centered_design"
      - name: "feature_post"
        field:
          element: "checkbox"
          label: "Feature Post"
          help: "Feature posts are displayed on the home page. Check the box if this post is a feature post."
          value: ""
      - name: "width"
        field:
          element: "select"
          label: "Post Width"
          help: "Select full to make main post image appear as full-width on the single post page. Select half to make the image appear half-width. The default value is set to half"
          placeholder: "half"
          options:
            - name: "Half"
              value: "half"
            - name: "Full"
              value: "full"
      - name: "image"
        field:
          element: "text"
          label: "Image File Name"
          help: "Enter the name of the image file with the extension, ie: featuredpost2.png"
          value: ""
          placeholder: ""
      - name: "image_alt"
        field:
          element: "text"
          label: "Image Alt Text"
          help: "Descriptive text for each image - important for universal design"
          value: ""
          placeholder: "Edify Blog Post Image"
      - name: "short_description"
        field:
          element: "textarea"
          label: "Short Description"
          help: "This text will be displayed on the blog listing page"
          value: ""
          placeholder: ""
